repl_dict = {
    "is not equal to": "!=",
    "is not equals to": "!=",
    "not equals to": "!=",
    "not equal to": "!=",
    "not equals": "!=",
    "not equal": "!=",
    "is not": "!=",
    "is equal to": "=",
    "equals to": "=",
    "equal to": "=",
    "equals": "=",
    "equal": "=",
    "not": "!",
    "addition": "+",
    "add": "+",
    "plus": "+",
    "subtract": "-",
    "minus": "-",
    "multiplied by": "*",
    "multiply by": "*",
    "multiply": "*",
    "into": "*",
    "divided by": "/",
    "divide by": "/",
    "divide": "/",
    "modulus": "%",
    "modulo": "%",
    "mod": "%",
    "is less than equals to": "<=",
    "is less than equal to": "<=",
    "is less than": "<",
    "is greater than equals to": ">=",
    "is greater than equal to": ">=",
    "is greater than": ">",
    "is more than equals to": ">=",
    "is more than equal to": ">=",
    "is more than": ">",
    "less than equals to": "<=",
    "less than equal to": "<=",
    "less than": "<",
    "greater than equals to": ">=",
    "greater than equal to": ">=",
    "greater than": ">",
    "more than equals to": ">=",
    "more than equal to": ">=",
    "more than": ">",
}