corr_list = [
    "start a for loop",
    "repeat",
    "set a flag to False",
    "for each pair of keys",
    "if the keys are in the wrong order then",
    "swap the keys",
    "set the flag to True",
    "end if",
    "nextpair",
    "until flag is not set",
    "pair",
    "until",
    "for",
    "loop",
    "end",
    "keys",
    "Algorithm start",
    "set",
    "LoopCounter",
    "third element",
    "for every",
    "array",
    "existing",
    "increment",
    "endfor",
    "Set loopcounter to 0",
    "to",
    "10",
]
