corr_list = [
    "Pseudo Code",
    "Programming",
    "C Language",
    "start",
    "for loop",
    "repeat",
    "flag",
    "set",
    "False",
    "for each",
    "keys",
    "then",
    "wrong order",
    "swap",
    "end if",
    "nextpair",
    "pair",
    "until",
    "for",
    #  "keys",
    "Algorithm",
    "LoopCounter",
    "element",
    "for every",
    "array",
    "existing",
    "increment",
    "end for",
    # Srishti
    "input",
    "sum",
    "average",
    "divide by",
    "Initialize",
    "output",
    "pivot",
    "Partition",
    "element",
    "recursively",
    "basis of",
    "Declare",
    "Declare",
    "integer",
    "variable",
    "repeat number times",
    "current value",
    "end loop",
    "sort",
    "recursively",
    # Rajdeep
    "pre",
    "remainder",
    "code",
    "odd",
    "even",
    "else",
    "prime",
    "false",
    "true",
    "factor",
    "end",
    "pseudocode"
]
