corr_list = [
<<<<<<< HEAD
    "start",
    "pseudocode",
    "for",
    "end",
    "loop",
    "repeat",
    "flag",
    "set",
    "false",
=======
    "Pseudo Code",
    "Programming",
    "C Language",
    "start",
    "for loop",
    "repeat",
    "flag",
    "set",
    "False",
    "for each",
    "keys",
    "then",
    "wrong order",
    "swap",
    "end if",
    "nextpair",
>>>>>>> 7b484d8b47527887e7db3d057a20adca01be5b1c
    "pair",
    "keys"
    "if",
    "then",
    "order",
    "swap",
    "true",
    "next",
    "until",
<<<<<<< HEAD
    "algorithm",
    "set",
    "counter",
    "element",
    "every",
    "array",
    "existing",
    "increment",
=======
    "for",
    #  "keys",
    "Algorithm",
    "LoopCounter",
    "element",
    "for every",
    "array",
    "existing",
    "increment",
    "end for",
>>>>>>> 7b484d8b47527887e7db3d057a20adca01be5b1c
    # Srishti
    "input",
    "sum",
    "average",
    "divide",
    "initialize",
    "output",
    "pivot",
    "partition",
    "element",
    "recursively",
<<<<<<< HEAD
    "basis",
    "declare",
    "integer",
    "variable",
    "repeat",
    "store",
    "assign",
    "value",
    "sort",
    "recursively",
    "partition",
    "pivot",
=======
    "basis of",
    "Declare",
    "Declare",
    "integer",
    "variable",
    "repeat number times",
    "current value",
    "end loop",
    "sort",
    "recursively",
>>>>>>> 7b484d8b47527887e7db3d057a20adca01be5b1c
    # Rajdeep
    "pre",
    "remainder",
    "code",
    "odd",
    "even",
    "else",
    "prime",
    "false",
    "true",
    "factor",
    "summation",
    "print",
    "not"
]
